name: Continuous Integration Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: scraper-artifacts
          path: .
  
  test:
    
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v2
        with:
          name: scraper-artifacts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          scrapy crawl vgg-hotitems
